Interest.blog-1.1/views/api.py
# -*- coding: utf8 -*-

import requests
from flask import Blueprint, url_for, g, jsonify, request
from utils.public import logger, timeChange

api_page = Blueprint("api", __name__)

@api_page.route("/comments/")
def ApiComments():
    res  = {"code": 0, "data": [], "msg": None}
    args = dict(short_name=g.plugins['DuoshuoComment']['shortName'], range="all", num_items=request.args.get("limit", 10))
    try:
        data = requests.get("http://api.duoshuo.com/sites/listTopThreads.json", params=args, timeout=5, headers={"User-Agent": "Interest.blog/www.saintic.com"}).json()
        blog = [ _ for _ in data.get("response") if _.get("comments") != 0 and _.update(created_at=timeChange(_['created_at'])) == None ]
    except Exception,e:
        logger.error(e, exc_info=True)
    else:
        res.update(data=blog, code=data["code"])
    logger.info(res)
    return jsonify(res)

Interest.blog-1.1/views/front.py
# -*- coding: utf8 -*-

import requests, datetime, SpliceURL
from urlparse import urljoin
from werkzeug.contrib.atom import AtomFeed
from flask import Blueprint, g, render_template, request, redirect, url_for, make_response, abort
from config import SSO, PLUGINS, BLOG
from utils.public import logger, md5, BaiduActivePush
from libs import get_blogId_data, get_user_profile, get_user_blog, get_index_list, get_index_data

front_page = Blueprint("front", __name__)

@front_page.route("/")
def index():
    return render_template("front/index.html")

@front_page.route('/blog/<int:bid>.html')
def blogShow(bid):
    data = get_blogId_data(bid)
    if data:
        if PLUGINS['BaiduActivePush']['enable'] in ("true", "True", True):
            original = True if data.get("sources") == "原创" else False
            BaiduActivePush(request.url, original=original)
        return render_template("front/blogShow.html", blogId=bid, data=data)
    else:
        return abort(404)

@front_page.route("/blog/edit/")
def blogEdit():
    blogId = request.args.get("blogId")
    if g.signin and blogId:
        data = get_blogId_data(blogId)
        if data and g.username == data.get("author") or g.username == "admin":
            return render_template("front/blogEdit.html", blogId=blogId, data=data)
    return redirect(url_for(".login"))

@front_page.route("/blog/write/")
def blogWrite():
    if g.signin:
        return render_template("front/blogWrite.html")
    else:
        return redirect(url_for(".login"))

@front_page.route("/blog/resources/")
def blogResources():
    return render_template("front/resources.html")

@front_page.route("/home/")
def home():
    if g.signin:
        user = get_user_profile(g.username)
        blog = get_user_blog(g.username)
        return render_template("front/home.html", user=user, blog=blog, blogLength=len(blog))
    else:
        return redirect(url_for(".login"))

@front_page.route("/home/profile/")
def profile():
    if g.signin:
        user = get_user_profile(g.username)
        return render_template("front/profile.html", user=user)
    else:
        return redirect(url_for(".login"))

@front_page.route('/login/')
def login():
    if g.signin:
        return redirect(url_for(".index"))
    else:
        query = {"sso": True,
           "sso_r": SpliceURL.Modify(request.url_root, "/sso/").geturl,
           "sso_p": SSO["SSO.PROJECT"],
           "sso_t": md5("%s:%s" %(SSO["SSO.PROJECT"], SpliceURL.Modify(request.url_root, "/sso/").geturl))
        }
        SSOLoginURL = SpliceURL.Modify(url=SSO["SSO.URL"], path="/login/", query=query).geturl
        logger.info("User request login to SSO: %s" %SSOLoginURL)
        return redirect(SSOLoginURL)

@front_page.route('/logout/')
def logout():
    SSOLogoutURL = SSO.get("SSO.URL") + "/sso/?nextUrl=" + request.url_root.strip("/")
    resp = make_response(redirect(SSOLogoutURL))
    resp.set_cookie(key='logged_in', value='', expires=0)
    resp.set_cookie(key='username',  value='', expires=0)
    resp.set_cookie(key='sessionId',  value='', expires=0)
    resp.set_cookie(key='time',  value='', expires=0)
    resp.set_cookie(key='Azone',  value='', expires=0)
    return resp

@front_page.route('/sso/')
def sso():
    ticket = request.args.get("ticket")
    logger.info("ticket: %s" %ticket)
    username, expires, sessionId = ticket.split('.')
    if expires == 'None':
        UnixExpires = None
    else:
        UnixExpires = datetime.datetime.strptime(expires,"%Y-%m-%d")
    resp = make_response(redirect(url_for(".index")))
    #resp.set_cookie(key="test", value="ok", expires=datetime.datetime.strptime(expires,"%Y-%m-%d"))
    #resp.set_cookie(key='test', value="ok", max_age=ISOString2Time(expires))
    resp.set_cookie(key='logged_in', value="yes", expires=UnixExpires)
    resp.set_cookie(key='username',  value=username, expires=UnixExpires)
    resp.set_cookie(key='sessionId', value=sessionId, expires=UnixExpires)
    resp.set_cookie(key='time', value=expires, expires=UnixExpires)
    resp.set_cookie(key='Azone', value="sso", expires=UnixExpires)
    return resp

@front_page.route("/google32fd52b6c900160b.html")
def google_search_console():
    return render_template("public/google32fd52b6c900160b.html")

@front_page.route("/robots.txt")
def robots():
    return """
User-agent: *
Disallow: 
Sitemap: http://www.saintic.com/sitemap.xml
    """

@front_page.route("/sitemap.xml")
def sitemap():
    resp = make_response(render_template("public/sitemap.xml", data=get_index_list()))
    resp.headers["Content-Type"] = "application/xml"    
    return resp

@front_page.route("/feed")
@front_page.route("/feed/")
def feed():
    data = get_index_data(limit=10)
    logger.debug(data)
    feed = AtomFeed('Interest.blog Feed', feed_url=request.url, url=request.url_root, subtitle="From the latest article in www.saintic.com")
    for article in data:
        feed.add(article['title'], unicode(article['content']),
                 content_type='html',
                 author=article['author'],
                 id=article['id'],
                 url=urljoin(request.url_root, url_for(".blogShow", bid=article['id'])),
                 updated=datetime.datetime.strptime(article['update_time'] or article['create_time'],"%Y-%m-%d"),
                 published=datetime.datetime.strptime(article['create_time'],"%Y-%m-%d"))
    return feed.get_response()

@front_page.route("/webscan_360_cn.html")
def webscan_360_cn():
    return render_template("public/webscan_360_cn.html")

Interest.blog-1.1/views/upload.py
# -*- coding: utf8 -*-

import os, requests
from utils.public import logger, gen_filename, UploadImage2Upyun
from flask import Blueprint, request, Response, url_for, redirect, g, jsonify
from werkzeug import secure_filename
from config import PLUGINS

upload_page             = Blueprint("upload", __name__)
BLOG_IMAGE_UPLOAD_DIR   = 'static/img/ImageUploads/'
AVATAR_IMAGE_UPLOAD_DIR = 'static/img/avatar/ImageUploads/'
BLOG_UPLOAD_FOLDER      = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), BLOG_IMAGE_UPLOAD_DIR)
AVATAR_UPLOAD_FOLDER    = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), AVATAR_IMAGE_UPLOAD_DIR)
ALLOWED_EXTENSIONS      = set(['png', 'jpg', 'jpeg', 'gif'])

#文件名合法性验证
allowed_file = lambda filename: '.' in filename and filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS

#对图片上传进行响应
@upload_page.route("/image/", methods=["POST",])
def UploadImage():
    editorType = request.args.get("editorType", "wangEditor")
    logger.debug(request.files)
    f = request.files.get("WriteBlogImage") or request.files.get("editormd-image-file")
    if f and allowed_file(f.filename):
        filename = secure_filename(gen_filename() + "." + f.filename.split('.')[-1]) #随机命名
        filedir  = os.path.join(upload_page.root_path, BLOG_UPLOAD_FOLDER)
        logger.info("get allowed file %s, its name is %s, save in %s" %(f, filename, filedir))
        if not os.path.exists(filedir):
            os.makedirs(filedir)
        f.save(os.path.join(filedir, filename))
        if PLUGINS['UpYunStorage']['enable']:
            imgUrl = "/interest.blog/blog/" + filename
            upres  = UploadImage2Upyun(os.path.join(filedir, filename), imgUrl)
            imgUrl = PLUGINS['UpYunStorage']['dn'].strip("/") + imgUrl
            logger.info("Blog to Upyun file saved, its url is %s, result is %s" %(imgUrl, upres))
        else:
            imgUrl = request.url_root + BLOG_IMAGE_UPLOAD_DIR + filename
            logger.info("Blog to local file saved in %s, its url is %s" %(filedir, imgUrl))
        if editorType == "wangEditor":
            res = Response(imgUrl)
            res.headers["ContentType"] = "text/html"
        else:
            res = jsonify(url=imgUrl, message=None, success=1)
            res.headers["ContentType"] = "application/json"
        res.headers["Charset"] = "utf-8"
        logger.debug(res)
        return res
    else:
        result = r"error|未成功获取文件，上传失败"
        logger.warn(result)
        if editorType == "wangEditor":
            res = Response(result)
            res.headers["ContentType"] = "text/html"
        else:
            res = jsonify(message=result, success=0)
            res.headers["ContentType"] = "application/json"
        res.headers["Charset"] = "utf-8"
        logger.debug(res)
        return res

@upload_page.route('/avatar/', methods=['POST','OPTIONS'])
def UploadProfileAvatar():
    logger.debug(request.files)
    f = request.files.get('file')
    # Check if the file is one of the allowed types/extensions
    if f and allowed_file(f.filename):
        filename = secure_filename(gen_filename() + "." + f.filename.split('.')[-1]) #随机命名
        filedir  = os.path.join(upload_page.root_path, AVATAR_UPLOAD_FOLDER)
        logger.info("get allowed file %s, its name is %s, save in %s" %(f, filename, filedir))
        if not os.path.exists(filedir):
            os.makedirs(filedir)
        f.save(os.path.join(filedir, filename))
        if PLUGINS['UpYunStorage']['enable']:
            imgUrl = "/interest.blog/avatar/" + filename
            upres  = UploadImage2Upyun(os.path.join(filedir, filename), imgUrl)
            imgUrl = PLUGINS['UpYunStorage']['dn'].strip("/") + imgUrl
            logger.info("Avatar to Upyun file saved, its url is %s, result is %s" %(imgUrl, upres))
        else:
            imgUrl   = "/" + AVATAR_IMAGE_UPLOAD_DIR + filename
            logger.info("Avatar to local file saved in %s, its url is %s" %(filedir, imgUrl))
        # return user home and write avatar url into mysql db.
        res = requests.put(g.apiurl + "/user/", timeout=5, verify=False, headers={'User-Agent': 'Interest.blog'}, params={"change": "avatar"}, data={"avatar": imgUrl, "username": g.username}).json()
        logger.info(res)
    return redirect(url_for('front.home'))

Interest.blog-1.1/templates/front/blogShow.html
{% extends "base/front.html" %}

{% block title %}{{ data['title'] }} | SaintIC Interest Blog Detail{% endblock %}

{% block head %}
  {%- if g.plugins['CodeHighlighting'] %}
  <link href="{{ url_for('static', filename='highlight/styles/googlecode.css') }}" rel="stylesheet">
  <script src="{{ url_for('static', filename='highlight/highlight.pack.js') }}"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  {% endif -%}
{% endblock %}

{% block content %}

<article class="post">

  <header class="post-header">
    <h1 class="post-title" itemprop="name headline">{{ data['title'] }}</h1>
        <!--<p class="post-meta">Author: {{ data['author'] }}</p>-->
        <p class="post-meta"><time datetime="2016-01-01T10:26:42+00:00" itemprop="datePublished">Create: {{ data['create_time'] }}</time></p>
    {% if data.get("update_time") %}
        <p class="post-meta"><time datetime="2016-01-01T10:26:42+00:00" itemprop="datePublished">Update: {{ data['update_time'] }}</time></p>
    {% endif %}
    {% if data['tag'] %}
        <p class="post-meta">Tags: 
        {% for tag in data['tag'].split() %}
            <a href="{{ url_for('front.blogResources', resources_type='tag', resources_data=tag) }}" target="_blank"><scan class="badge green">{{ tag }}</scan></a>&nbsp;
        {% endfor %}
        </p>
    {% endif %}
    {% if data['catalog'] %}
        <p class="post-meta">Catalog: <a href="{{ url_for('front.blogResources', resources_type='catalog', resources_data=data['catalog']) }}" target="_blank"><scan class="badge yellow">{{ data['catalog'] }}</scan></a></p>
    {% endif %}
    {% if data.get("sources") %}
        <p class="post-meta">Sources: <a href="{{ url_for('front.blogResources', resources_type='source', resources_data=data.get('sources')) }}" target="_blank">
        {% if data.get("sources") == "原创" %}
            <img src="{{ url_for('static', filename='img/icon/Original.gif') }}" /></a></p>
        {% elif data.get("sources") == "转载" %}
            <img src="{{ url_for('static', filename='img/icon/Reprint.gif') }}" /></a></p>
        {% elif data.get("sources") == "翻译" %}
            <img src="{{ url_for('static', filename='img/icon/Translate.gif') }}" /></a></p>
        {% endif %}
    {% endif %}
    {% if g.signin and g.username == data.get("author") or g.username == "admin" %}
    <p class="post-meta">
        <a href="{{ url_for('front.blogEdit', blogId=blogId) }}">编辑文章</a>&nbsp;
        {% if g.username == "admin" %}
        {% if data.top in ('true', 'True', True) %}
        <a href="javascript:setTop(false)">取消置顶</a>&nbsp;
        {% else %}
        <a href="javascript:setTop(true)">置顶文章</a>&nbsp;
        {% endif %}
        {% if data.recommend in ('true', 'True', True) %}
        <a href="javascript:setRecommend(false)">取消推荐</a>&nbsp;
        {% else %}
        <a href="javascript:setRecommend(true)">推荐文章</a>&nbsp;
        {% endif %}
        {% endif %}
    </p>
    {% endif %}
  </header>

  <div class="post-content" itemprop="articleBody">
    {{ data['content'] | safe }}
  </div>

  <div class="copyright">
    {%- if data.get("sources") == "原创" %}
    <pre style="max-width: 100%;"><code class="python hljs" codemark="1"><b>版权声明</b>：<br />
    本文为原创文章，由<a href="http://www.saintic.com" target="_blank">SainIC</a>创作和发表，版权所有，转载请注明作者及出处！<br />
    本文标题是：{{ data['title'] }}， 本文来源地址：<a href="{{ request.url }}">{{ request.url }}</a></code>
    </pre>
    {% endif -%}
    {%- if g.plugins['BaiduShare'] %}
    <!-- 百度分享插件 -->
    <div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more">分享给朋友</a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信">微信</a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博">新浪微博</a><a href="#" class="bds_sqq" data-cmd="sqq" title="分享到QQ好友">QQ好友</a><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间">QQ空间</a><a href="#" class="bds_huaban" data-cmd="huaban" title="分享到花瓣">花瓣</a><a href="#" class="bds_fbook" data-cmd="fbook" title="分享到Facebook">Facebook</a><a href="#" class="bds_twi" data-cmd="twi" title="分享到Twitter">Twitter</a><a href="#" class="bds_youdao" data-cmd="youdao" title="分享到有道云笔记">有道云笔记</a><a href="#" class="bds_mail" data-cmd="mail" title="分享到邮件分享">邮件分享</a></div>
    <script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"1","bdSize":"16"},"share":{"bdSize":16}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];</script>
    {% endif -%}
  </div>
</article>

{%- if g.plugins['DuoshuoComment']['enable'] %}
<!-- 多说评论框插件 start -->
  <div class="ds-thread" data-thread-key="{{ blogId }}" data-title="{{ data['title'] }}" data-url="{{ request.url }}"></div>
<!-- 多说评论框插件 end -->
{% endif -%}

{% endblock %}

{% block script %}
<script type="text/javascript">

{% if g.plugins['BaiduAutoPush'] %}
/* 百度自动推送插件 */
(function(){
    var bp = document.createElement('script');
    var curProtocol = window.location.protocol.split(':')[0];
    if (curProtocol === 'https') {
        bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';        
    }
    else {
        bp.src = 'http://push.zhanzhang.baidu.com/push.js';
    }
    var s = document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(bp, s);
})();
{% endif %}

{% if g.plugins['DuoshuoComment']['enable'] %}
/* 多说评论框公共JS代码 */
var duoshuoQuery = {short_name:"{{ g.plugins['DuoshuoComment']['shortName'] }}"};
  (function() {
    var ds = document.createElement('script');
    ds.type = 'text/javascript';ds.async = true;
    ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
    ds.charset = 'UTF-8';
    (document.getElementsByTagName('head')[0] 
     || document.getElementsByTagName('body')[0]).appendChild(ds);
  })();
{% endif %}

{% if g.plugins['360AutoPush'] %}
/* 360自动推送插件 */
(function(){
   var src = (document.location.protocol == "http:") ? "http://js.passport.qihucdn.com/11.0.1.js?0804a1ea6759eb5939e26ae7531fb05a":"https://jspassport.ssl.qhimg.com/11.0.1.js?0804a1ea6759eb5939e26ae7531fb05a";
   document.write('<script src="' + src + '" id="sozz"><\/script>');
})();
{% endif %}

{% if g.username == "admin" %}
// 设置或取消置顶文章
function setTop(value) {
    $.ajax({
        url: "{{ g.apiurl }}/misc?action=top&blogId={{ blogId }}&value=" + value,
        method: 'POST',
        datatype: 'json',
        success: function(res) {
            console.log(res);
            var res = res.success;
            if (res==true) {
                if(value==false) {
                    alert("取消置顶成功！");
                } else {
                    alert("置顶文章成功！");
                }
            } else {
                if(value==false) {
                    alert("取消置顶失败！");
                } else {
                    alert("置顶文章失败！");
                }
            }
            window.location.reload();
        },
        error: function(error){
            console.log(error);
        }
    });
}

// 设置或取消推荐文章
function setRecommend(value) {
    $.ajax({
        url: "{{ g.apiurl }}/misc?action=recommend&blogId={{ blogId }}&value=" + value,
        method: 'POST',
        datatype: 'json',
        success: function(res) {
            console.log(res);
            var res = res.success;
            if (res==true) {
                if(value==false) {
                    alert("取消推荐成功！");
                } else {
                    alert("推荐文章成功！");
                }
            } else {
                if(value==false) {
                    alert("取消推荐失败！");
                } else {
                    alert("推荐文章失败！");
                }
            }
            window.location.reload();
        },
        error: function(error){
            console.log(error);
        }
    });
}
{% endif %}
</script>
{% endblock %}

Interest.blog-1.1/templates/front/blogWrite.html
{% extends "base/front.html" %}

{% block title %}Interest Blog Write | SaintIC{% endblock %}

{% block head %}
{% if request.args.get("editor", "wangEditor") == "wangEditor" %}
  <!-- 引入wangEditor.css -->
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='wangEditor/css/wangEditor.min.css') }}">
{% else %}
  <!-- 引入Editor.md.css -->
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='Editor.md/css/editormd.min.css') }}">
{% endif %}
{% endblock %}

{% block content %}
<div>
    <h1>创作文章</h1>
    {%- if request.args.get("editor", "wangEditor") == "wangEditor" %}
    <h3>当前使用<a href="http://www.wangeditor.com/" target="_blank">wangEditor</a>富文本编辑器<sub><a href="{{ url_for('front.blogWrite', editor='Editor.md') }}">&nbsp;切换&nbsp;</a></sub></h3>
    <form id="CreateBlogFormId" method="" action="">
        <p>标题：<input type="text" style="width:300px;height:20px" name="title" placeholder="请在此处填写文章标题" required /><em style="color:red; front-size:bold">*</em></p>
        <p>标签：<input type="text" style="width:300px;height:20px" name="tag" placeholder="请在此处输入标签并以空格分割" required /></p>
        <p>分类：<input type="text" style="width:300px;height:20px" name="catalog" placeholder="请自定义输入分类或选择列表内条目" list="blog_catalogs" required /></p>
        <datalist id="blog_catalogs">
            <option>未分类</option>
        </datalist>
        <p>类型：
            <input type="radio" name="sources" value="原创" checked="checked">原创
            <input type="radio" name="sources" value="转载">转载 
            <input type="radio" name="sources" value="翻译">翻译
        </p>
        <textarea id="editor" style="height:500px; max-height:640;" name="content">
           <p>请输入文章内容...</p>
        </textarea>
        <input type="hidden" name="author" value="{{ g.username }}">
        <input type="hidden" name="editor" value="wangEditor">
        <input onclick=postForm() type="button" value="提交博客" class="button green" />
    </form>
    {% else%}
    <h3>当前使用<a href="http://pandao.github.io/editor.md/" target="_blank">Editor.md</a>富文本编辑器<sub><a href="{{ url_for('front.blogWrite', editor='wangEditor') }}">&nbsp;切换&nbsp;</a></sub></h3>
    <form id="CreateBlogFormId" method="" action="">
        <p>标题：<input type="text" style="width:300px;height:20px" name="title" placeholder="请在此处填写文章标题" required /><em style="color:red; front-size:bold">*</em></p>
        <p>标签：<input type="text" style="width:300px;height:20px" name="tag" placeholder="请在此处输入标签并以空格分割" required /></p>
        <p>分类：<input type="text" style="width:300px;height:20px" name="catalog" placeholder="请自定义输入分类或选择列表内条目" list="blog_catalogs" required /></p>
        <datalist id="blog_catalogs">
            <option>未分类</option>
        </datalist>
        <p>类型：
            <input type="radio" name="sources" value="原创" checked="checked">原创
            <input type="radio" name="sources" value="转载">转载 
            <input type="radio" name="sources" value="翻译">翻译
        </p>
        <div id="editor">
            <textarea style="display:none;" name="content"># 请输入文章内容...</textarea>
        </div>
        <input type="hidden" name="author" value="{{ g.username }}">
        <input type="hidden" name="editor" value="Editor.md">
        <input onclick=postForm() type="button" value="提交博客" class="button green" />
    </form>
    {% endif -%}
</div>

{% endblock %}

{% block script %}
{% if request.args.get("editor", "wangEditor") == "wangEditor" %}
<!--引入jquery和wangEditor.js-->
<script type="text/javascript" src="{{ url_for('static', filename='wangEditor/js/wangEditor.min.js') }}"></script>
<script type="text/javascript">
    // 获取元素
    var div = document.getElementById('editor');
    // 生成编辑器
    var editor = new wangEditor(div);

    // 为当前的editor配置密钥
    editor.config.mapAk = 'rsG1HfOkrldOGdI53TMI9rAdxGuzb0PI';

    // 取消粘贴过滤
    editor.config.pasteFilter = true;

    // 插入代码时的默认语言
    editor.config.codeDefaultLang = 'python';

    /*
       上传图片功能，文档地址：http://www.kancloud.cn/wangfupeng/wangeditor2/113990；
       后台文档地址：http://www.kancloud.cn/wangfupeng/wangeditor2/115736;
       后台需要配置一个获取表单上传图片并保存的路由。
    */
    editor.config.uploadImgUrl = "{{ url_for('upload.UploadImage', editorType='wangEditor') }}";
    editor.config.uploadImgFileName = 'WriteBlogImage';

    // 创建编辑器
    editor.create();
</script>
{% else %}
<!--引入jquery和Editor.md.js-->
<script type="text/javascript" src="{{ url_for('static', filename='Editor.md/js/editormd.min.js') }}"></script>
<script type="text/javascript">
    var Editor;
    $(function() {
        Editor = editormd({
                id      : "editor",
                width   : "100%",
                height  : 500,
                syncScrolling : "single",
                path    : "/static/Editor.md/lib/",
                // 开启上传图片功能
                imageUpload : true,
                imageFormats : ['png', 'jpg', 'jpeg', 'gif'],
                imageUploadURL : "{{ url_for('upload.UploadImage', editorType='Editor.md') }}",
                /*
                     上传的后台只需要返回一个 JSON 数据，结构如下：
                     {
                        success : 0 | 1,           // 0 表示上传失败，1 表示上传成功
                        message : "提示的信息，上传成功或上传失败及错误信息等。",
                        url     : "图片地址"        // 上传成功时才返回
                     }
                */
                emoji : true,                 // Emoji表情
                saveHTMLToTextarea : true,    // 保存 HTML 到 Textarea
                searchReplace : true,
                flowChart : true,             // 开启流程图支持，默认关闭
                sequenceDiagram : true,       // 开启时序/序列图支持，默认关闭,
        });
    });
</script>
{% endif %}

<script type="text/javascript">
    // 获取文章分类信息
    $.ajax({
        url: "{{ g.apiurl }}/blog?get_catalog_list=true",
        method: 'GET',
        datatype: 'json',
        success: function(res) {
            console.log(res);
            var data = res.data;
            var str2 = '';
            for(i=0; i<data.length; i++) {
                catalog = data[i];
                str2 += '<option>' + catalog + '</option>';
            };
            document.getElementById('blog_catalogs').innerHTML=str2;
        },
        error: function(error){
            console.log(error);
        }
    });

    // 提交文章数据
    function postForm() {
        {%- if request.args.get("editor", "wangEditor") == "wangEditor" %}
        blog = $('#CreateBlogFormId').serialize();
        {% else %}
        data = $('#CreateBlogFormId').serializeArray();
        blog = {"title": data[0].value, "tag": data[1].value, "catalog": data[2].value, "sources": data[3].value, "content": Editor.getHTML(), "author": data[6].value};
        {% endif -%}
        console.log(blog);
        $.ajax({
            url: '{{ g.apiurl }}/blog/',
            method: 'POST',
            datatype: 'json',
            data: blog,
            success: function(res) {
                console.log(res);
                if (res.code == 0){
                    alert("提交文章成功！")
                    if ( isNaN(res.data) ) {
                        location.reload(true);
                    } else {
                        window.location="/blog/" + res.data + ".html";
                    }
                } else {
                    alert("提交文章失败，请重试提交或报告错误！\n错误原因是：" + res.msg);
                }
            },
        });
    };
</script>
{% endblock %}