demo/myapp/__init__.py
#coding=utf-8
from flask import Flask,request,session
from myapp.extension import socketio,db,login_manager,pagedown,moment,\
                            bootstrap,babel,admin,toolbar,mogodb,mail,photos,videos,celery,filecache
import flask_whooshalchemyplus
from flask_uploads import configure_uploads
from config import config,Config
from myapp.defs import cn_to_utc,utc_to_cn
from flask_sslify import SSLify
import re




#setup_periodic_tasks()

login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    from .main import main as main_blueprint
    from .auth import auth as auth_blueprint
    from .mongo import mongo as mongo_blueprint
    from .socket_io import socket_io as socket_io_blueprint
    app = Flask(__name__)
    #判断客户端是否是手机
    @app.before_request
    def before_first_request():
        User_Agent = request.headers['User-Agent']
        is_mobile = re.findall('Mobile', User_Agent)
        if is_mobile:
             session['mobile_flags'] = 1
        else:
            session['mobile_flags']=0
    app.config['BABEL_DEFAULT_LOCALE']='zh_CN'
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    babel.init_app(app)
    bootstrap.init_app(app)
    configure_uploads(app, photos)
    configure_uploads(app, videos)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    pagedown.init_app(app)
    login_manager.init_app(app)
    admin.init_app(app)
    socketio.init_app(app)
    filecache.init_app(app)
    #toolbar.init_app(app)
    mogodb.init_app(app)
    celery.conf.update(app.config)
    flask_whooshalchemyplus.init_app(app)

    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint, url_prefix='/auth')
    app.register_blueprint(socket_io_blueprint)
    app.register_blueprint(mongo_blueprint,url_prefix='/mongo')
    sslify = SSLify(app)

    #自定义过滤器截取字符数
    @app.template_filter('filter')
    def filter(s):
        return s[0:300]

    @app.template_filter('utctime')
    def utctime(s):
        utctime=cn_to_utc(s)
        return utctime

    @app.template_filter('nowtime')
    def nowtime(s):
        nowtime=utc_to_cn(s)
        return nowtime
    # 或者
    # def filter(s):
    #     return s[0:300]
    # app.jinja_env.filters['filter'] = filter

    #添加jiaja2循环扩展支持break,continue
    app.jinja_env.add_extension('jinja2.ext.loopcontrols')
    return app

demo/myapp/admin/__init__.py
from .import views

demo/myapp/admin/views.py
#coding=utf-8
from flask_admin import  BaseView, expose
from flask import url_for
from flask_login import current_user
from flask_admin.contrib.sqla import ModelView
from ..models import Post
from myapp.extension import db
import os as op
from myapp.extension import admin
from flask_admin.contrib.fileadmin import FileAdmin




class MyView(BaseView):
    #改函数返回真才能访问该导航
    def is_accessible(self):
        return current_user.is_authenticated  #用户登录返回真。
    # http://127.0.0.1:5000/welcome/my/
    @expose('/')
    def index(self):
        url = url_for('.view')
        return self.render('admin/home.html',url=url)
    #http://127.0.0.1:5000/welcome/my/view
    @expose('/view')
    def view(self):
        return self.render('admin/view.html')

class hello1(BaseView):
    # http://127.0.0.1:5000/welcome/test1/
    @expose('/')
    def index(self):
        return self.render('admin/hello1.html')
class hello2(BaseView):
    # http://127.0.0.1:5000/welcome/test2/
    @expose('/')
    def index(self):
        return self.render('admin/hello2.html')
class hello3(BaseView):
    # http://127.0.0.1:5000/welcome/test3/
    @expose('/')
    def index(self):
        url = url_for('my.view') #MyView.view函数
        return self.render('admin/hello3.html',url=url)





class UserView(BaseView):
    #改函数返回真才能访问该导航
    def is_accessible(self):
        return current_user.is_authenticated  #用户登录返回真。
    # http://127.0.0.1:5000/welcome/my/
    @expose('/')
    def index(self):
        url = url_for('.view')
        return self.render('admin/home.html',url=url)
    #http://127.0.0.1:5000/welcome/my/view
    @expose('/view')
    def view(self):
        return self.render('admin/view.html')

class MyV1(ModelView):
    def is_accessible(self):
        if current_user.is_authenticated :
            return True
        return False
    can_create = False

    column_labels = {
        'id':u'序号',
        'body' : u'文章',
        'timestamp':u'发布时间',
        'author_id':u'作者id'
    }
    column_list = ('id', 'body','timestamp','author_id')
    def __init__(self, session, **kwargs):
        super(MyV1, self).__init__(Post,session, **kwargs)



admin.add_view(MyView(name='新闻',endpoint='my'))
admin.add_view(hello1(name='Hello 1', endpoint='test1', category='信息'))
admin.add_view(hello2(name='Hello 2', endpoint='test2', category='信息'))
admin.add_view(hello3(name='Hello 3', endpoint='test3', category='信息'))
path = op.join(op.dirname(__file__), '../static/img')
print(path)
admin.add_view(FileAdmin(path, '/static/', name='文件',endpoint='file'))
admin.add_view(MyV1(db.session, name=u'管理新闻'))

demo/myapp/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views, errors
from ..models import Permission
@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

demo/myapp/main/views.py
#coding=utf-8
from time import sleep
from flask import render_template, redirect, url_for,request,flash,abort,current_app,make_response,jsonify,session
from flask.ext.sqlalchemy import get_debug_queries
from . import main
from .forms import EditProfileForm,EditProfileAdminForm,PostForm,EditArticleForm,SearchArticleForm
from .. import db
from flask_login import login_required,current_user
from ..models import User,Role,Post,Comment,Whoosh,Permission,Heart,Article,Collect,Follow
from ..celery_email import sub
from ..decorators import admin_required, permission_required
from ..defs import datedir
import os,shutil
from ..extension import photos,filecache
import bleach
from markdown import markdown
#报告缓慢的数据库查询
@main.after_app_request
def after_request(response):
    for query in get_debug_queries():
        if query.duration >= current_app.config['FLASKY_SLOW_DB_QUERY_TIME']:
            current_app.logger.warning(
            'Slow query: %s\nParameters: %s\nDuration: %fs\nContext: %s\n' %(query.statement, query.parameters, query.duration,query.context))
    return response

# @main.route('/test')
# def test():
#     r=sub.delay()
#     print(r.result)
#     print(r.successful())
#     print(r.backend)
#     i=0
#     while r.successful()==False:
#         i=i+1
#         sleep(4)
#         print(i)
#     return r.status

@main.route('/is_admin')
@login_required
@admin_required
def for_admins_only():
    return "For administrators!"

@main.route('/moderator')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def for_moderators_only():
    return "For comment moderators!"

@main.route('/user/<username>')
def user(username):

    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    user_flag =(request.cookies.get('user_flag', '1'))
    print(user_flag)
    page=request.args.get('page',1,type=int)
    if user_flag=='2':
        pagination=user.articles.filter(Article.disabled!=2).paginate(
            page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
            error_out=False)
        articles = pagination.items
        return render_template('user.html', user=user,articles=articles,user_flag=user_flag,pagination=pagination)
    if user_flag=='3':
        pagination=Article.query.join(Collect,Collect.user_id==user.id).filter(Article.id==Collect.article_id).filter(Article.disabled!=2).paginate(
            page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
            error_out=False)
        articles = pagination.items
        return render_template('user.html', user=user,articles=articles,user_flag=user_flag,pagination=pagination)
    user_flag ='1'
    pagination=user.posts.paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    return render_template('user.html', user=user, posts=posts, user_flag=user_flag, pagination=pagination)

@main.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        current_user.img=form.img.data
        db.session.add(current_user)
        db.session.commit()
        flash('Your profile has been updated.')
        return redirect(url_for('.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    form.img.data=current_user.img
    return render_template('edit_profile.html', form=form)

@main.route('/edit-profile/<int:id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(id):
    user = User.query.get_or_404(id)
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        user.email = form.email.data
        user.username = form.username.data
        user.confirmed = form.confirmed.data
        user.role = Role.query.get(form.role.data)
        user.name = form.name.data
        user.location = form.location.data
        user.about_me = form.about_me.data
        db.session.add(user)
        flash('The profile has been updated.')
        return redirect(url_for('.user', username=user.username))
    form.email.data = user.email
    form.username.data = user.username
    form.confirmed.data = user.confirmed
    form.role.data = user.role_id
    form.name.data = user.name
    form.location.data = user.location
    form.about_me.data = user.about_me
    return render_template('edit_profile.html', form=form, user=user)
@main.route('/user_img')
@login_required
def user_img():
    img  = User.query.filter_by(id=current_user.id).first()
    return img.img

@main.route('/img/<username>')
def img(username):
    try:
        img  = User.query.filter_by(username=username).first()
    except:
        pass
    else:img  = User.query.filter_by(username='chen').first()
    return img.img


@main.route('/', methods=['GET', 'POST'])
#@filecache.memoize(timeout=50)
def index():
    form = PostForm()
    # current_app.logger.debug('A value for debugging')
    # current_app.logger.warning('A warning occurred (%d apples)', 42)
    # current_app.logger.error('An error occurred')

    if current_user.can(Permission.WRITE_ARTICLES) and \
    form.validate_on_submit():
        if form.cls.data=='':
            form.cls.data=None
        post = Post(body=form.body.data,author=current_user._get_current_object(),file_urls=form.file_urls.data,cls=form.cls.data)
        db.session.add(post)

        return redirect(url_for('.index'))
    page = request.args.get('page', 1, type=int)
    show_followed = False
    if current_user.is_authenticated:
        show_followed = bool(request.cookies.get('show_followed', ''))
    if show_followed:
        query = current_user.followed_posts
    else:
        query = Post.query
    pagination = query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items

    if session.get('mobile_flags',None):
        return render_template('index.html', form=form, posts=posts,
                               show_followed=show_followed, pagination=pagination)
    return render_template('index.html', form=form, posts=posts,
                           show_followed=show_followed, pagination=pagination)
@main.route('/articles', methods=['GET','POST'])
def articles():
    form=SearchArticleForm()
    page = request.args.get('page', 1, type=int)
    print ('1')



    show_article_followed = False
    if current_user.is_authenticated:
        show_article_followed = bool(request.cookies.get('show_article_followed', ''))


    #搜索部分
    if form.validate_on_submit():
        pagination=Article.query.whoosh_search(form.keyword.data.strip())\
            .order_by(Article.timestamp.desc()).paginate(
            page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
            error_out=False)
        articles = pagination.items
        return render_template('articles.html', show_followed=show_followed, form=form,
                               articles=articles, pagination=pagination)

    if show_article_followed:
        query = current_user.follwed_articles
    else:
        query = Article.query
    query=query.filter(Article.disabled==0)
    pagination = query.order_by(Article.timestamp.desc()).paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    articles = pagination.items

    return render_template('articles.html',show_article_followed=show_article_followed,form=form,
                           articles=articles,pagination=pagination)
@main.route('/article/<int:id>',methods=['GET','POST'])
def article(id):
    page = request.args.get('page', 1, type=int)
    article=Article.query.filter_by(id=id).first()
    article.add_views
    pagination=Comment.query.filter_by(article=article).order_by(Comment.timestamp.desc()).paginate(
        page,per_page=current_app.config['FLASKY_ARTICLE_COMMENT_PER_PAGE'],error_out=False
    )
    comments = pagination.items
    if request.method=='POST' and \
        current_user.can(Permission.WRITE_ARTICLES):
        body=request.form.get('body')
        comment=Comment(body=body,author=current_user._get_current_object(),\
               article_id=article.id)
        db.session.add(comment)
        return redirect(url_for('.article',id=article.id))
    return render_template('article.html',article=article,comments=comments,pagination=pagination)


@main.route('/edit/article', methods=['GET', 'POST'])
@login_required
def edit_article():
    form=EditArticleForm()
    if current_user.can(Permission.WRITE_ARTICLES) and \
        form.validate_on_submit():
        # #过滤script标签
        # allowed_tags = ['script']
        # body=bleach.linkify(bleach.clean(markdown(form.body.data, output_format='html'), tags=allowed_tags, strip=False))
        article=Article(body=form.body.data,title=form.title.data.strip(),author=current_user._get_current_object())
        db.session.add(article)
        return redirect(url_for('.articles'))
    return render_template('edit_article.html',form=form)
#编辑文章
@main.route('/update/article/<int:id>', methods=['GET', 'POST'])
@login_required
def update_article(id):
    article = Article.query.get_or_404(id)
    if current_user != article.author :
        abort(403)
    form = EditArticleForm()
    if form.validate_on_submit():
        article.body = form.body.data
        article.title=form.title.data
        db.session.add(article)
        flash('The post has been updated.')
        return redirect(url_for('.article', id=article.id))
    form.title.data=article.title
    form.body.data = article.body
    return render_template('update_article.html', form=form,id=article.id)

demo/myapp/mongo/views.py
from flask import Blueprint, request, redirect, render_template, url_for
from flask.views import MethodView
from . import mongo
from myapp.mogomodels import Post
@mongo.route('/list')
def list():
    posts = Post.objects.all()
    return render_template('mongo/list.html', posts=posts)
@mongo.route('/detail/<slug>')
def detail(slug):
    post = Post.objects.get_or_404(slug=slug)
    return render_template('mongo/detail.html', post=post)

demo/myapp/socket_io/__init__.py
from flask import Blueprint
socket_io = Blueprint('socket_io', __name__)
from . import views

demo/myapp/socket_io/views.py
from flask import render_template,session
from .import socket_io
@socket_io.route('/msg/')
def msg():
    return render_template('socketio/msg.html')

demo/myapp/templates/_article.html
<ul class="articles" style="padding: 0px">
{% for article in articles %}
    {% if current_user!=article.author %}
        {% if article.disabled==1 %}
            {%  continue  %}
        {% endif %}
    {% endif %}
    <div  class="row article" style="padding-top: 50px;margin-left: 0px">
    <div class="article-head">
        <div style="float: left">
            <a href="{{ url_for('.user', username=article.author.username) }}" >
                <img class="media-object img-circle " src="{{ url_for('static',filename=article.author.img )}}" alt="..." style=" width:40px;height: 40px;">
            </a>
        </div>
        <div style="float: left;margin-left: 2%">
            <p style="font-size: 16px;margin-bottom: 0px">{{ article.author.username }}</p>
            <p style="font-size: 13px;color: #87928a;margin-top: 0px">{{ moment(article.timestamp).fromNow(refresh=True) }}</p>
        </div>
        {% if current_user==article.author %}
        <div style="float: right">
            <a href="{{ url_for('.disabled_article',id=article.id) }}">
                {% if article.disabled==0  %}
                可见
                {% else %}
                不可见
                {% endif %}
            </a>
        </div>
        {% endif %}
    </div>
    <div class="article-content" style="clear: both">
        <div class="article-title">
            <h4 >
                <a style="color: black;text-decoration: none" href="{{ url_for('.article',id=article.id) }}"
                   onmouseover="article_focus($(this))"
                    onmouseout="article_out($(this))">
                    {{ article.title }}
                </a></h4>
        </div>


        <div class="article-body" style="font-size: 14px;color: #3c3836;float: left">
            {% if article.body_text|length >300 %}
                {{ article.body_text|safe|filter }}...
{#                <p style="margin-top: 10px"><a href="{{ url_for('.article',id=article.id) }}">阅读全文</a></p>#}
            {% else %}
             {{ article.body_text }}
            {% endif %}
        <p style="margin-top: 10px;color: #5f6d64;font-size: small"><label>阅读{{ article.views }}</label>
            <label>点赞{{ article.hearts.count() }}</label>
            <label>评论{{ article.comments.count() }}</label>
        </p>

        </div>
    </div>
    </div>
{% endfor %}
<hr style="clear: both">
</ul>

demo/myapp/templates/_comments.html
<div class="comment-body">
{% if comment.disabled %}
<p></p><i>This comment has been disabled by a moderator.</i></p>
{% endif %}
{% if moderate or not comment.disabled %}
{% if comment.body_html %}
{{ comment.body_html | safe }}
{% else %}
{{ comment.body }}
{% endif %}
{% endif %}
</div>
{% if moderate %}
<br>
{% if comment.disabled %}
<a class="btn btn-default btn-xs" href="{{ url_for('.moderate_enable',
id=comment.id, page=page) }}">Enable</a>
{% else %}
<a class="btn btn-danger btn-xs" href="{{ url_for('.moderate_disable',
id=comment.id, page=page) }}">Disable</a>
{% endif %}
{% endif %}

demo/myapp/templates/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages(left_edge= 1 ,left_current=3,right_current=3,right_edge=1) %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

demo/myapp/templates/articles.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}椰壳-文章{% endblock %}
{% block page_content %}
    <div class="content" style="margin-right: 1%;margin-left: 1%;">
        {# 页头#}
        <div class="row header" >
            {#<div class="col-md-7">
                <img src="{{ url_for('static',filename='img/article_back.jpg') }}" style="width: 100%;height: auto">
            </div>
            <div class="col-md-5">
                <img src="{{ url_for('static',filename='img/article_back.jpg') }}" style="width: 100%;height: auto">

            </div>
#}

        </div>


        {#主体#}
        <div class="row mian">

            {# 左侧#}
            <div id="content-right" class="col-md-8 col-sm-8   " style="margin-top: 15px;padding-left: 8%">

                <div id="articles" class="row" >
                    <div class="article-tabs" >


                        <ul class="nav nav-tabs" style="margin-top: 20px;margin-bottom: 20px; font-size: 20px">
                            <li{% if not show_article_followed %} class="active"{% endif %}><a href="{{ url_for('.show_article_all') }}">全部</a></li>
                            {% if current_user.is_authenticated %}
                                <li{% if show_article_followed %} class="active"{% endif %}><a href="{{ url_for('.show_article_followed') }}">关注</a></li>
                                <li style="float: right;" ><a href="{{ url_for('.edit_article') }}" style="color:#FF6103" ><span class="glyphicon glyphicon-pencil" ></span>发表</a></li>
                            {% endif %}

                        </ul>
                        {% include '_article.html' %}
                    </div>
                    {#动态#}
                </div>


                {#分页部分#}
                <div id="page" class="row">
                    <div class="pagination ">
                        {{ macros.pagination_widget(pagination, '.articles') }}
                    </div>
                </div>

                {#主体#}
            </div>


            <div id="content-left" class="col-md-3 col-sm-3" style="margin-left: 5%;margin-top: 80px">
            <div  id="form">
                <form method="post" action="{{ url_for('.articles') }}" class="input-group">
                    {{ form.csrf_token }}
                    {{ form.keyword(class="form-control" ,placeholder="搜索...") }}
                    <span class="input-group-btn">
                    {{ form.submit(class="btn btn-default") }}
                    </span>
                </form>
            </div>
            </div>
            {#右侧#}

        </div>



        <div class=" row footer"></div>

    </div>

{% endblock %}


{% block scripts %}
    {{ super() }}
    <script type="text/javascript">
    function article_focus(obj) {
     obj.css('color','#337ab7');
    }
    function article_out(obj) {
     obj.css('color','black');
    }
    </script>
{% endblock %}

demo/myapp/templates/edit_article.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}椰壳-发表文章{% endblock %}
{% block head %}

    <link rel="stylesheet" type="text/css"
          href="{{ url_for('static', filename='pro/wangEditor-2.1.23/dist/css/wangEditor.min.css') }}"
          xmlns="http://www.w3.org/1999/html">
    {#使用代码高亮#}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='pro/highlight/styles/dark.css') }}">
    <script type="text/javascript" src="{{ url_for('static', filename='pro/wangEditor-2.1.23/dist/js/lib/jquery-1.10.2.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='pro/wangEditor-2.1.23/dist/js/wangEditor.min.js')}}"></script>
    {{ super() }}
{% endblock %}
{% block page_content %}
    <form method="post" action="{{ url_for('main.edit_article') }}" >
        <div style="padding-top: 50px;padding-bottom: 10px;text-align: center">
      {{ form.title.label(style="padding-right:15px;") }}{{ form.title(id="tilte" ,style="width:400px",placeholder="标题不能为空") }}
        </div>
        {{ form.file.label() }}{{ form.file() }}<p style="color: #5c6370">只支持doc,docx,xls.xlsx,pdf,txt,zip后缀的文件，不能超过30M</p>
    <hr style="clear: both;margin-top: 10px" >
    <div style="text-align: center;padding-bottom: 80px">

            <div>{{ form.csrf_token  }}</div>

            {{ form.body(id="div1",style="height: 500px;display:none;") }}
            </br>
            <div>{{ form.submit(class="btn btn-warning",style="float: left;padding-left:20px;padding-right:20px" ) }}</div>
            <div><button id="btn" style="float: right" class="btn-default">获取文本</button></div>
            <div><button id="btn1" style="float: right" class="btn-default">销毁编辑器</button></div>
            <div><button id="btn2" style="float: right" class="btn-default">恢复编辑器</button></div>
    </div>
    </form>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script type="text/javascript">
    {#id#}
    var editor = new wangEditor('div1');
    editor.config.uploadImgUrl = '{{ url_for('auth.upimage') }}';
    editor.config.uploadImgFileName = 'myFileName';

    editor.create();
    //初始化编辑器的内容
    {% if data %}
     editor.$txt.html('{{data.context|safe}}');
    {% endif %}

    // 上传图片（举例）


    // 配置自定义参数（举例）
{#    editor.config.uploadParams = {#}
{##}
{#    };#}



    $("#btn").click(function () {
         var html = editor.$txt.html();
        alert(html);
    });
    $('#btn1').click(function () {
    // 销毁编辑器
        editor.destroy();
    });

    $('#btn2').click(function () {
        // 恢复编辑器
        editor.undestroy();
    });
</script>
{% endblock %}

demo/myapp/templates/edit_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - Edit Profile{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Your Profile</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

demo/myapp/templates/followers.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}Flasky - {{ title }} {{ user.username }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>{{ title }} {{ user.username }}</h1>
</div>
<table class="table table-hover followers">
    <thead><tr><th>User</th><th>Since</th></tr></thead>
    {% for follow in follows %}
    {% if follow.user != user %}
    <tr>
        <td>
            <a href="{{ url_for('.user', username = follow.user.username) }}">
                <img class="img-rounded" src="{{ follow.user.img}}">
                {{ follow.user.username }}
            </a>
        </td>
        <td>{{ moment(follow.timestamp).format('L') }}</td>
    </tr>
    {% endif %}
    {% endfor %}
</table>
<div class="pagination">
    {{ macros.pagination_widget(pagination, endpoint, username = user.username) }}
</div>
{% endblock %}

demo/myapp/templates/index_footer.html
jiao

demo/myapp/templates/index_head.html
nihao

demo/myapp/templates/index_left.html
youce

demo/myapp/templates/index_right.html
you

demo/myapp/templates/post.html
{% extends "base.html" %}
{% block title %}Flasky - Post{% endblock %}
{% block page_content %}
{% include '_posts.html' %}
{% endblock %}
{% block scripts %}

     {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='pro/img_viewer/viewer.css') }}">
    <script type="text/javascript" src="{{ url_for('static', filename='pro/img_viewer/viewer.js')}}"></script>

<script type="text/javascript">
    $('.images').viewer();
    function heart(id) {

        $.ajax({ url: "/heart", data:{'id':id},type:'post', dataType: 'json',
            success: function(data){
                if (data){
                    alert('ok');
                }
            }
        });
    }
</script>
{% endblock %}